export const newsItem = [
  {
    id: "1",
    title: "Chief Minister of Haryana to visit Ratia today",
    description:
      "The Chief Minister will visit Ratia today and inaugurate several development projects.",
    publishedAt: new Date(Date.now() - (12 * 60 * 60 * 1000)).toISOString(),
    isBreaking: true,
    isRecent: true,
    location: "Mandi Ratia",
    views: Math.floor(Math.random() * 1500) + 200,
    readTime: `${Math.floor(Math.random() * 4) + 2} min read`,
    imageUrl:
      "./Haryana-chief-minister-Nayab-Saini-during-the-swea_1742931698976.jpg",
  },
  {
    id: "2",
    title: "Digital education begins in Ratia's schools",
    description:
      "New equipment has been made available for digital education in all government schools of the city.",
    publishedAt: new Date(Date.now() - (1 * 60 * 60 * 1000)).toISOString(),
    isBreaking: true,
    views: Math.floor(Math.random() * 1500) + 200,
    readTime: `${Math.floor(Math.random() * 4) + 2} min read`,
    imageUrl: "./education2.jpg",
    location: "Gov. School, Ratia",
    isRecent: true,
  },
  {
    id: "3",
    title: "Weather alert for farmers: Rain expected next week",
    description:
      "The weather department has issued a heavy rain alert for farmers next week and advised precautions for crops.",
    publishedAt: new Date(Date.now() - (5 * 60 * 60 * 1000)).toISOString(),
    views: Math.floor(Math.random() * 1500) + 200,
    readTime: `${Math.floor(Math.random() * 4) + 2} min read`,
    imageUrl: "./agriculture.jpg",
    category: "Weather",
    isBreaking: false,
    isRecent: false,
    location: "Ratia",
  },
  {
    id: "4",
    title: "Regional sports fair to be held in Ratia",
    description:
      "A regional sports fair will be organized in Ratia next month, with athletes from various districts of Haryana participating.",
    publishedAt: new Date(Date.now() -  (12 * 60 * 60 * 1000)).toISOString(),
    views: Math.floor(Math.random() * 1500) + 200,
    readTime: `${Math.floor(Math.random() * 4) + 2} min read`,
    imageUrl: "./sport.jpg",    
    category: "Sports",
    isBreaking: false,
    isRecent: false,
    location: "Ratia Stadium",
  },
  {
    id: "5",
    title: "New Community Center Opens in Downtown Area",
    description:
      "State-of-the-art facility includes library, sports complex, and meeting spaces for local residents.",
    category: "Community",
    isBreaking: false,
    isRecent: true,
    views: 850,
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    readTime: "3 min read",
    location: "Tehsil Complex",
    imageUrl:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
  },
  {
    id: "6",
    title: "Local Business District Sees 15% Growth This Quarter",
    description:
      "Small businesses report increased foot traffic and sales as community support programs show positive results.",
    category: "Local Business",
    isBreaking: false,
    isRecent: true,
    isLead: false,
    views: 620,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    readTime: "4 min read",
    location: "Mini Secterate",
    imageUrl:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
  },
  {
    id: "7",
    title: "Annual Food Festival Returns to City Park",
    description:
      "Three-day event featuring local vendors, live music, and family activities scheduled for next weekend.",
    category: "Events",
    isBreaking: false,
    isRecent: true,
    isLead: false,
    views: 1200,
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    readTime: "2 min read",
    location: "City Park",
    imageUrl:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop",
  },
  {
    id: "8",
    title: "Road Construction Project Begins on Main Street",
    description:
      "Infrastructure improvements expected to enhance traffic flow and pedestrian safety in the downtown core.",
    category: "City News",
    isBreaking: true,
    isRecent: true,
    isLead: false,
    views: 950,
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    readTime: "3 min read",
    location: "Tohana Road",
    imageUrl:
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&h=600&fit=crop",
  },
  {
    id: "9",
    title: "High School Basketball Team Advances to Regional Finals",
    description:
      "Local team's impressive season continues with victory over neighboring district rivals.",
    category: "Sports",
    isBreaking: false,
    isRecent: true,
    isLead: false,
    views: 780,
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    readTime: "3 min read",
    location: "Ratia High School",
    imageUrl:
      "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&h=600&fit=crop",
  },
  {
    id: "10",
    title: "New Public Transportation Route Connects Suburban Areas",
    description:
      "Enhanced bus service aims to improve connectivity between residential neighborhoods and city center.",
    category: "City News",
    isBreaking: false,
    isRecent: false,
    isLead: false,
    views: 540,
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    readTime: "4 min read",
    location: "Various",
    imageUrl:
      "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop",
  },
];
